### PR TITLE
added new classroom

### PR DESCRIPTION
**Pull request by arifmamon**
#new classroom - 

> _Our Planets_

### CODE REVIEW

**Comment by gauravsinhaweb** [comment]
Hi @arifmamon, Nice work, Can you create an issue in https://github.com/gauravsinhaweb/EduSmart/issues and add more objects in a subject ( at least 3) then PR again.

**Comment by arifmamon** [comment]
Sorry but Issue for adding more Classrooms ?

**Comment by gauravsinhaweb** [comment]
@arifmamon  Yes and in that issue, can you add more content/ 3D objects (at least 3) in the new subject you created 'Our planet'. So the user will have some resources to study in a particular subject.

**Comment by arifmamon** [comment]
> @arifmamon Yes and in that issue, can you add more content/ 3D objects (at least 3) in the new subject you created 'Our planet'. So the user will have some resources to study in a particular subject.

oh ok i got now .

**Pull request merged**
