### PR TITLE
Structered imports & If else to Switch & cleaned code #27

### PR DESCRIPTION
**Pull request by dddqwerty**
Okay i changed details if else to switch case and structured & cleaned imports.

### CODE REVIEW

**Comment by gauravsinhaweb** [comment]
Hi @dddqwerty , Thanks for doing this PR, It was necessary. If you could do more clean coding, I would appreciate it and feel free to do more PRs. 💯

**Comment by dddqwerty** [comment]
Hii @gauravsinhaweb, Okay i will add index on assets.

**Comment by gauravsinhaweb** [comment]
@dddqwerty , Go for it 👍 , and if possible make reusable components so that, the performance of the site might get better.

**Comment by dddqwerty** [comment]
I converted all svgs to react comp.

**Pull request merged**
