### PR TITLE
Fixed contributors page and headings

### PR DESCRIPTION
**Pull request by mihirharshe**
- Added icons of GitHub and LinkedIn and placed the names in a single row to tidy the page.

- Centered rest of the headings.

### CODE REVIEW

**Comment by gauravsinhaweb** [comment]
Hey @mihirharshe , can you update the contributor's page and then PR.

**Comment by mihirharshe** [comment]
@gauravsinhaweb Do you mean to update the contributors from https://github.com/gauravsinhaweb/EduSmart/graphs/contributors ?

**Comment by gauravsinhaweb** [comment]
@mihirharshe to add all the members who contributed. Pic for reference:

**Comment by mihirharshe** [comment]
@gauravsinhaweb Yes on it.

**Pull request merged**
