### PR TITLE
New Sidebar UI changes and Scrolling feature 

### PR DESCRIPTION
**Pull request by piyush-mahajan**
# Description

1. **Scrolling Blur Effect:** When the user scrolls the page, a subtle blur effect is applied to the navigation bar. This effect helps draw the user's attention to the navigation bar and creates a sense of depth as the user interacts with the content.

2. **Clear Visibility on Stop:** After the user stops scrolling, the blur effect is removed, and the navigation bar becomes clearly visible. This behavior ensures that the navigation options are easily accessible when needed.

**Implementation Details:**

- The `Navbar` component now utilizes React's `useState` and `useEffect` hooks to track scrolling and apply the blur effect.

- A `showing` state variable is introduced to determine whether the navbar should be clearly visible when scrolling stops.

- A `showTimeout` variable is used to manage the timeout for removing the blur effect when scrolling stops.

- CSS styles have been added to control the blur effect and clear visibility.

**Testing:**

I have thoroughly tested this feature on different devices and browsers to ensure that it works as intended. I have also verified that the blur effect is applied while scrolling and removed promptly when scrolling stops.

Fixes # (issue no.) 
#105 
## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

-  My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

**Reviewer Note:**

Please review and provide feedback on the implementation, code quality, and user experience improvements. Thank you!
# ATTACH SCREENSHOTS
image
on scroll
image

### CODE REVIEW

**Comment by gauravsinhaweb** [comment]
@piyush-mahajan could you fix the extra margin to the left of the sidepanel

**Comment by piyush-mahajan** [comment]
Ya sure👍

**Comment by piyush-mahajan** [comment]
so i have change the sidebar according to you, can you merge it✌️

**Comment by gauravsinhaweb** [comment]
> so i have change the sidebar according to you, can you merge it✌️

 2. After the user stops scrolling, the blur effect is removed, and the navigation bar becomes clearly visible. This behavior ensures that the navigation options are easily accessible when needed.
 
 The current implementation only blurs navigation but does not disable the blur effect while the user stays for a page for any point of scroll,
 make sure you the 2nd point you mentioned in the issue is implemented, then we are good to go with this PR.

**Comment by piyush-mahajan** [comment]
Ok ✌️

**Comment by piyush-mahajan** [comment]
change the scroll feature, have a look ✌️and merge it 🙂

**Review by gauravsinhaweb — APPROVED** [review]

**Pull request merged**
